### PR TITLE
Use npm-run-all for npm build task

### PR DESCRIPTION
**Pull request by arekkas**
Resolves build issues on windows

### CODE REVIEW

**Comment by omnidan** [comment]
@arekkas Thanks for the PR! Why did you change the version from `beta9-1` to `beta9`? (I can't do `beta10` because npm thinks that's lower than `beta9`)

**Comment by arekkas** [comment]
sorry, no real reason. Should I change it back?

**Comment by omnidan** [comment]
@arekkas yes please :grin:

**Comment by omnidan** [comment]
released `beta9-2` with this change

**Pull request merged**
