### PR TITLE
Add definitions for TypeScript

### PR DESCRIPTION
**Pull request by forabi**
This helps IDEs like VS Code and Atom with TypeScript plugins understand the types of different functions and exports and warn about issues with typos/incompatible types... etc

### CODE REVIEW

**Comment by omnidan** [comment]
Thank you for the PR, @forabi :grin: I am not too familiar with typescript, is it normal to start type names with a lowercase character? I think that's a bit confusing (maybe I'm just used to the naming conventions of types in other languages, like Haskell, though).

**Comment by forabi** [comment]
I'm not too familiar either :smile: 

Actually this is the first time I use TypeScript in a large project and VS Code kept complaining about the missing definition file. So I had to write it myself and reference it manually.

I thought it might be a good idea to have them in the package itself.

As for the naming of types, I am not sure, I have seen many projects with different naming conventions, some prefix types with a `T` and interfaces with an `I`. Some just use a capital letter.

I see your point however, I've updated the PR to keep names consistent.

**Comment by omnidan** [comment]
@forabi Thanks for the quick response! Looks good to me now :grin:

**Comment by jfstephe** [comment]
@forabi - quick question.... I tried running 'typings install redux-undo@1.0.0-beta9-2' to get the TS definitions but it failed. Can you tell me how are you getting the types?

Many thanks!

**Comment by forabi** [comment]
@jfstephe You do not need to use `typings install`, definition files are included in the npm package and they should be automatically picked up by TypeScript language service just by doing `npm install redux-undo`

**Comment by jfstephe** [comment]
ah - indeed. I'm using jspm and I think https://github.com/Microsoft/TypeScript/issues/6012 is biting me. Thanks for jolting my grey cells :-).

**Comment by jessewatson** [comment]
Newbie question (typescript related)... I am not seeing any type definitions after an "npm install redux-undo" - it looks like npm is pulling down redux-undo@0.6.1 by default. When I tried "npm install redux-undo@1.0.0-beta9-2", it says "invalid" and appears to be the unbuilt source tree.

Do I need to git clone it and build it myself? Are there docs for this?

**Comment by omnidan** [comment]
@jessewatson did you try installing via `npm install redux-undo@beta` (as described in the README)?

**Comment by jessewatson** [comment]
@omnidan - Wow - no idea how I missed that. Thanks!

**Comment by omnidan** [comment]
@jessewatson no worries :wink: glad it works now :grin:

**Pull request merged**
