### PR TITLE
Add clearHistoryTypes (#126)

### PR DESCRIPTION
**Pull request by Bear-Foot**

### CODE REVIEW

**Comment by omnidan** [comment]
Thanks for the PR, @Bear-Foot! What do you think about allowing arrays in `clearHistoryType` instead of making a new field? That way we wouldn't bloat the API too much.

**Comment by Bear-Foot** [comment]
Here we go. I didn't want to break the switch case, but computed case values feel weird, what do you think ?

**Comment by omnidan** [comment]
@Bear-Foot sorry for the late response. It looks fine, but if you want to avoid using computed values in the case statement, you can always turn it into an array if it's not specified as such. Then you always have the same check if the type is in the array. I think that would be a bit simpler.

**Comment by omnidan** [comment]
@Bear-Foot I haven't heard back from you yet - do you still want to change anything in regards to my comment above, or is this PR ready to merge now? Please let me know :smile:

**Comment by Bear-Foot** [comment]
Hey sorry I was really busy and didn't free some time for this, I'll do this by the end of the week :)

**Comment by omnidan** [comment]
Thanks a lot @Bear-Foot! I published `beta9-4` with this change :ok_hand:

**Pull request merged**
