### PR TITLE
Depend on babel-preset-es2015

### LINKED ISSUE #35: v0.6.0 (latest on npm) includes .babelrc incompatible with babel@6
The react native packager crashes on the `.babelrc.stage`.  Just wondering why you haven't published at least a minor bump with the new .babelrc?

Maybe there's something I can help with?

### PR DESCRIPTION
**Pull request by danscan**
Should resolve #35

### CODE REVIEW

**Comment by omnidan** [comment]
@danscan thank you! Are you sure this is the correct way to solve this issue, though? I don't think you should put babel stuff into `dependencies`. Are you running into the same problem with [redux](https://github.com/reactjs/redux), which has [all babel dependencies in `dev`](https://github.com/reactjs/redux/blob/master/package.json#L66)?

**Comment by danscan** [comment]
The best way would actually be to add a build script, publish it to npm built, and set the `package.json`'s `main` to something like `lib/index.js`.

**Comment by danscan** [comment]
Let's do that instead.  I can create another PR later today when I have some more time.

**Comment by omnidan** [comment]
@danscan it should be published to npm built and `main` is set too:

> "prepublish": "npm run lint && npm run test && npm run clean && npm run build"

> "main": "lib/index.js"

**Pull request closed without merging**
