### PR TITLE
Chai Unit Tests

### PR DESCRIPTION
**Pull request by pl12133**
A few unit tests with Mocha and Chai.

### CODE REVIEW

**Comment by omnidan** [comment]
@pl12133 Thanks a lot :grin: Can you fix the linter errors? https://travis-ci.org/omnidan/redux-undo/builds/95086104

**Comment by pl12133** [comment]
Yup! Working through it now, thanks for taking a look at it.

**Comment by pl12133** [comment]
I don't usually work with a linter so that took a few tries, I should probably use one myself from now on.

**Comment by omnidan** [comment]
@pl12133 Awesome! Thank you so much :smile:

Glad you learned some things and yes, linters are awesome :wink:

**Comment by pl12133** [comment]
Yup I just installed a eslint myself. I'm glad the tests all work, thanks.

**Comment by omnidan** [comment]
@pl12133 it's probably easiest to just use the [JS standard style](http://standardjs.com/). I made an eslint config for that if you want to use it (or you can just copy the one redux-undo uses): https://github.com/touchlay/eslint-config-touchlay

**Comment by pl12133** [comment]
@omnidan Thanks for the link, I tried [touchlay](https://github.com/touchlay/eslint-config-touchlay) out, as well as [airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb). I like standard a lot more than airbnb, but I think I am not ready to let go of my semicolons yet so I will go with [semistandard](https://github.com/Flet/eslint-config-semistandard) right now. Now I have 400 lint errors in my project to fix!

Thanks for the help.

**Comment by omnidan** [comment]
@pl12133 Haha, sounds great :smile: :+1: Thanks again for the contribution!

**Pull request merged**
