### PR TITLE
Unit Tests Should Respect `initialHistory`

### PR DESCRIPTION
**Pull request by pl12133**
Unit tests should not fail if `initialHistory` is defined in the configuration.

Also fixed error in the wording of one test.

These tests are made anticipating that #29 will be merged.

### CODE REVIEW

**Comment by omnidan** [comment]
Thanks a lot :+1:

Could you [squash](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Squashing-Commits) the commits, please? :smile:

I'll merge this after #29 gets merged.

**Comment by pl12133** [comment]
OK all squashed, I've been wondering how to squash commits, so hopefully its done right!

**Comment by omnidan** [comment]
Thank you - looks good! Still waiting on #29 before I merge this, though. :sweat_smile:

**Comment by omnidan** [comment]
@pl12133 Can you please have a look at it again? :grin: #29 had some changes and now this PR is conflicting.

**Comment by pl12133** [comment]
@omnidan Conflicts resolved! I will be away for a short while so if there are any more changes to be made on my part they will have to wait a few weeks. Good luck on the 1.0 release!

**Comment by omnidan** [comment]
Thank you so much @pl12133 - I cloned your repo and during the `npm run lint` step of `npm install` I got [a weird crash](https://github.com/eslint/eslint/issues/5125#issuecomment-178130379).

**Comment by omnidan** [comment]
Alright - looks like it's an eslint issue, so I'll merge this. Thanks a lot! :ok_hand:

**Comment by omnidan** [comment]
I'll revert this until it's fixed because it breaks CI.

**Comment by omnidan** [comment]
This was a `babel-eslint` issue in a minor version upgrade which caused CI to fail (or your local version if you did `rm -rf node_modules` and `npm install`).

It is fixed now, so I have re-merged the PR and everything is fine now. (sorry for the mess, I thought reverting would fix CI :sweat_smile:)

**Comment by pl12133** [comment]
That's odd, glad it all got sorted out :+1:

**Pull request merged**
