### PR TITLE
Add neverSkipReducer option to undoable, resolves #129

### LINKED ISSUE #129: Run child reducer on redux-undo actions as well
At the moment, redux-undo skips the child reducer when an action is triggered that is known to redux-undo, for example [here](https://github.com/omnidan/redux-undo/blob/master/src/reducer.js#L157-L161):

```jsx
      case config.undoType:
        res = undo(history)
        debug.log('perform undo')
        debug.end(res)
        return res
```

Unfortunately, I have a use case where I need to execute the reducer there as well. I am aware that this is a very specific use case which is why I think that this should be configurable:

```jsx
      case config.undoType:
        res = undo(history)
        debug.log('perform undo')
        debug.end(res)
        return config.neverSkipReducer
          ? { ...res, present: reducer(res.present, action) }
          : res
```

### PR DESCRIPTION
**Pull request by arekkas**

### CODE REVIEW

**Comment by arekkas** [comment]
I will add a note to the docs and a test if you ( @omnidan ) are ok with merging this.

**Comment by omnidan** [comment]
@arekkas sounds good :+1:

**Comment by arekkas** [comment]
Awesome! I've added some docs and a test suite where `neverSkipReducer` is false :) By the way, travis fails because of coveralls, tests pass just fine :)

**Comment by arekkas** [comment]
@omnidan if it's possible, I would love to see a release after merge. It's currently a blocking issue for me :)

**Comment by omnidan** [comment]
Thanks! :grin:

**Comment by omnidan** [comment]
I also released a new version, @arekkas - let me know if everything works fine for you now :)

**Comment by arekkas** [comment]
Hm, I can't seem to find a version on [npm](https://www.npmjs.com/package/redux-undo) nor on [github](https://github.com/omnidan/redux-undo/releases), did I miss something?

**Comment by omnidan** [comment]
@arekkas it is published under the `beta` tag on npm (like the other beta releases) :wink: 

you can install it by doing: `npm install --save redux-undo@beta` or `redux-undo@1.0.0-beta9-1` (unfortunately, npm thinks `beta10` is lower than `beta9`, so I had to do a workaround and call it `beta9-1`)

**Comment by arekkas** [comment]
ah, awesome, thanks!


Am 11.11.2016 um 20:16 schrieb Daniel Bugl:

**Pull request merged**
