### PR TITLE
WIP - Added basic example in this repo

### PR DESCRIPTION
**Pull request by tiemevanveen**
Added a basic example.
Most code is copied over from redux repo, but made some adjustments.

- [ ] fix hmr reloading
- [ ] tests like: https://github.com/reactjs/redux/tree/master/examples/counter/test

### CODE REVIEW

**Comment by tiemevanveen** [comment]
image

Dunno why I can't HMReload the reducer.. @pl12133 do you spot the problem?

**Comment by tiemevanveen** [comment]
@omnidan you okay with adding a very basic example to the repo? I've found the boilerplate a bit too much for a basic example

**Comment by omnidan** [comment]
@tiemevanveen looks really nice :+1: I prefer this to the boilerplate, too.

**Comment by tiemevanveen** [comment]
Okay cool. If you have some time, could you maybe check what I did wrong? HMR is not working..

**Comment by pl12133** [comment]
@tiemevanveen I took a quick look at it and couldn't figure out the problem with HMR, I'll keep trying.

**Comment by tiemevanveen** [comment]
Haha weird isn't it.. I just don't get it

**Comment by omnidan** [comment]
@tiemevanveen @pl12133 any updates on this?

**Comment by tiemevanveen** [comment]
Nah, I don't get what is going wrong. Please feel free to close it and create something else that IS working :)

**Comment by omnidan** [comment]
@tiemevanveen it's alright, we already have the `todos-with-undo` example, should be enough for now :wink:

**Pull request closed without merging**
