### PR TITLE
Commit changes from `npm install` on clean repo

### PR DESCRIPTION
**Pull request by dbkaplun**

### CODE REVIEW

**Comment by omnidan** [comment]
@dbkaplun what is the idea behind this PR?

**Comment by omridevk** [comment]
@dbkaplun 
I think this PR is about the fact that package-lock file is not up to date, at least as far as I understood, running npm install on the repo you will see changes in the package-lock.json file.

**Comment by omnidan** [comment]
@omridevk thanks for explaining!

@dbkaplun thanks for the PR! can you update it again now (since it's been a while that this PR was created)?

**Comment by omnidan** [comment]
I did this myself now, thanks for the hint though!

**Comment by omridevk** [comment]
@omnidan 
Thanks :) and happy to help.

**Pull request closed without merging**
