### PR TITLE
Resolve #202: Add document of undo-redo batch of actions with custom groupBy

### LINKED ISSUE #202: How can i Undo or Redo a batch of actions at the same time ?
```js
undoable: undoable(undoReducer, {
    filter: function includeAction() {
        return action.type.match('$$')
    }
})
```

### PR DESCRIPTION
**Pull request by gaopinghuang0**
This method remains the ability to group by action types but also enables us to group a batch of actions.
- [x] Group by action types by default
- [x] Group batch actions on demand, with `start()` and `end()`

### CODE REVIEW

**Comment by gaopinghuang0** [comment]
Thanks for your reply. 

I rebased the branch on the upstream master, but it seems that I made a mistake that messed up the commit history. So I close this PR  and create a new PR #249. Thanks.

**Comment by nmay231** [comment]
Thank you! And I totally get it, rebasing is hard sometimes.

Here's a little tip for future reference about how to rebase. The easiest situation was when you just had the commit adding the example file.

```sh
git checkout undo-redo-batch-actions # switch to the branch that you are rebasing
git rebase master # rebase onto master
# make new changes and commit and then:
git push origin undo-redo-batch-actions --force # --force is required since remote and local have diverged
```
Of course `--force` is dangerous, so use it with care. If you are uncertain whether to use it or not, it would be better to recreate a PR like you did.

Now, I was also able to recover this PR and merge it nicely into a test branch on my machine. To do that, I used `git log --graph --oneline` and looked at the commits. This is one of the most useful commands, and I think it should be the default honestly. But anyways I got this

```
* 9e11610 (HEAD -> gaopinghuang0-undo-redo-batch-actions) move example to 'docs/examples' folder and link to it from the FAQ
*   37772fe merge
|\  
| * 70d2ab7 add document of undo-redo batch of actions with custom groupBy
* | 5675185 add document of undo-redo batch of actions with custom groupBy
* |   8b3ba62 (origin/master, origin/HEAD, master) Merge pull request #232 from Asatelit/patch-1
|\ \  
```
Using `git diff` I was saw that `70d2ab7` was your original commit and in `9e11...` you moved it and put a label in the FAQ. `5675` was somehow a duplicate of `70d2` but with a ton of other commits/garbage. To fix this I used `git rebase HEAD~3 --interactive` because I wanted to change the last three commits (`3777` was an empty merge commit and doesn't count here).

**Comment by gaopinghuang0** [comment]
Your suggestion is great! I was afraid of using `--force`. Now I understand rebasing better. 

Thank you so much!

**Comment by nmay231** [comment]
For sure! In fact, I accidentally commented that too soon and reopened the PR. Everyone makes mistakes :joy:

**Pull request closed without merging**
