### PR TITLE
Upgrading dist and examples to webpack 2

### PR DESCRIPTION
**Pull request by jcperez-ch**
📓 :

- Use webpack 2 to bundle the `UMD` distribution.
- Use webpack 2 to run the examples.

Nothing more, nothing less.

### CODE REVIEW

**Comment by jcperez-ch** [comment]
@omnidan I think this is minor, but still something that would happen eventually. Let me know your thoughts.

**Comment by jcperez-ch** [comment]
@davidroeca comments?

**Comment by davidroeca** [comment]
@jcperez-ch I have no qualms here but I'm not very well-acquainted with the publishing process (or is it automatic on a version change?)

I'd say we should wait on @omnidan since he set it up

**Comment by jcperez-ch** [comment]
@omnidan any updates for this one?

**Comment by omnidan** [comment]
@jcperez-ch @davidroeca sorry it took so long - looks good to me and the examples still seem to work, merging :grin: thanks for the PR!

**Comment by omnidan** [comment]
released `beta9-9-3` with this PR merged

**Pull request merged**
